In [3]:
import pandas as pd

In [15]:
df = pd.read_csv('train.csv')

In [16]:
df

id                                              title   
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...  \
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author   
0                                  Darrell Lucus  \
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[20800 rows x 5 columns]

In [17]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [18]:
df=df.dropna()

In [19]:
df

id                                              title   
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...  \
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author   
0                                  Darrell Lucus  \
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[18285 rows x 5 columns]

In [20]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [22]:
x = df.drop('label',axis=1)


In [23]:
y= df['label']

In [24]:
x.shape

(18285, 4)

In [25]:
y.shape

(18285,)

In [28]:
voc_size =5000

In [29]:
message = x.copy()

In [30]:
message.shape

(18285, 4)

In [58]:
messages = message.reset_index(inplace =True)

In [59]:
import tensorflow as tf


In [61]:
tf.__version__

'2.17.0'

In [128]:
from tensorflow.keras.layers import Embedding 
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense 
from tensorflow.keras.layers import Dropout

In [129]:
import nltk
import re
from nltk.corpus import stopwords

#### Dataset proprocessing

In [130]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [131]:
corpus = []
for i in range(0,len(message)):
    review = re.sub('[^a-zA-Z]',' ',message['title'][i])
    review =review.lower()
    review = review.split()
    review =[ps.stem(word) for word in review if word not in set(stopwords.words('english'))]
    review =' '.join(review)
    corpus.append(review)

In [64]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

##### One Hot reprresentation

In [65]:
one_hot_repre = [one_hot(word,voc_size) for word in corpus]
one_hot_repre

[[668, 676, 1839, 1843, 3467, 1878, 1878, 1588, 597, 3942],
 [4516, 3057, 2820, 735, 4714, 2787, 642],
 [2566, 702, 2878, 4587],
 [3079, 160, 1864, 4477, 3873, 180],
 [734, 4714, 1481, 4022, 1440, 922, 4714, 4976, 1730, 982],
 [3422,
  2728,
  2094,
  882,
  3632,
  4870,
  359,
  3936,
  3423,
  3261,
  832,
  1691,
  1593,
  3128,
  642],
 [2606, 2050, 4661, 460, 4399, 4440, 4150, 4609, 1819, 2657, 1466],
 [3741, 2871, 4705, 67, 517, 2119, 4870, 58, 1819, 2657, 1466],
 [498, 4974, 341, 4153, 80, 1084, 175, 1016, 4870, 1717],
 [4578, 3066, 3034, 2722, 2018, 2991, 1999, 3844],
 [3502, 964, 4461, 335, 799, 179, 206, 403, 4236, 3744, 922],
 [4477, 803, 3467, 1084, 4870, 517],
 [2531, 4395, 1598, 3443, 4360, 2626, 1250, 2474, 222],
 [1740, 327, 1635, 2278, 4899, 682, 2552, 1819, 2657, 1466],
 [1486, 2356, 2605, 3991, 3351, 1819, 2657, 1466],
 [911, 4272, 416, 1717, 1915, 4231, 4054, 4572, 4864, 4517],
 [3571, 4923, 3057],
 [3095, 1182, 3488, 3082, 4870, 3775, 1866, 642],
 [199, 4919, 2820

###### Embedding Representation

In [134]:
sent_length = 20
embbedded_docs = pad_sequences(one_hot_repre,padding ='pre',maxlen =sent_length)


In [77]:
embbedded_docs 

array([[   0,    0,    0, ..., 1588,  597, 3942],
       [   0,    0,    0, ..., 4714, 2787,  642],
       [   0,    0,    0, ...,  702, 2878, 4587],
       ...,
       [   0,    0,    0, ..., 1819, 2657, 1466],
       [   0,    0,    0, ..., 3303, 1402,  561],
       [   0,    0,    0, ..., 4954, 3544,  836]])

In [135]:
dim =40

In [136]:
# Creating Model

model = Sequential()
model.add(Embedding(voc_size,40,input_length =sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation ='sigmoid'))
model.compile(loss ='binary_crossentropy',optimizer ='adam',metrics =['accuracy'])
model.summary()


C:\Users\urp20\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_13 (Embedding)             │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_13 (LSTM)                       │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_12 (Dense)                     │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [91]:
embbedded_docs[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0, 4516, 3057, 2820,  735, 4714, 2787,  642])

In [92]:
embbedded_docs[2]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0, 2566,  702, 2878, 4587])

In [137]:
import numpy as np

In [138]:
x_final = np.array(embbedded_docs)
y_final= np.array(y)

In [96]:
x_final.shape

(18285, 20)

In [97]:
y_final.shape

(18285,)

In [139]:
from sklearn.model_selection import train_test_split

In [140]:
x_train,x_test,y_train,y_test = train_test_split(x_final,y_final,test_size= 0.33,random_state =42)

In [141]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs =5,batch_size=15)

Epoch 1/5
817/817 ━━━━━━━━━━━━━━━━━━━━ 26s 26ms/step - accuracy: 0.8339 - loss: 0.3412 - val_accuracy: 0.9167 - val_loss: 0.1974
Epoch 2/5
817/817 ━━━━━━━━━━━━━━━━━━━━ 22s 27ms/step - accuracy: 0.9493 - loss: 0.1312 - val_accuracy: 0.9183 - val_loss: 0.2039
Epoch 3/5
817/817 ━━━━━━━━━━━━━━━━━━━━ 15s 19ms/step - accuracy: 0.9663 - loss: 0.0933 - val_accuracy: 0.9185 - val_loss: 0.2093
Epoch 4/5
817/817 ━━━━━━━━━━━━━━━━━━━━ 15s 18ms/step - accuracy: 0.9774 - loss: 0.0658 - val_accuracy: 0.9201 - val_loss: 0.2290
Epoch 5/5
817/817 ━━━━━━━━━━━━━━━━━━━━ 15s 18ms/step - accuracy: 0.9836 - loss: 0.0445 - val_accuracy: 0.9152 - val_loss: 0.2573


In [142]:
y_pred = model.predict(x_test)

189/189 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step


In [143]:
y_pred

array([[9.9489886e-01],
       [3.2263060e-04],
       [1.8247814e-03],
       ...,
       [1.4016670e-05],
       [9.6584076e-01],
       [9.8307812e-01]], dtype=float32)

In [144]:
y_pred = np.where(y_pred>0.6,1,0)
y_pred

array([[1],
       [0],
       [0],
       ...,
       [0],
       [1],
       [1]])

In [145]:
from sklearn.metrics import confusion_matrix

In [146]:
confusion_matrix(y_test,y_pred)

array([[3148,  271],
       [ 261, 2355]], dtype=int64)

In [147]:
from sklearn.metrics import accuracy_score

In [148]:
accuracy_score(y_test,y_pred)

0.911847555923778

In [149]:
from sklearn.metrics import classification_report

In [150]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.92      0.92      3419
           1       0.90      0.90      0.90      2616

    accuracy                           0.91      6035
   macro avg       0.91      0.91      0.91      6035
weighted avg       0.91      0.91      0.91      6035

